export const ONBOARDING = {
    LOGIN_TO: "Login to",
    TRIA: "tria",
    DEMO: "Demo",
    CONTINUE_WITH_GOOGLE: "Continue with Google",
    CONTINUE_WITH_X: "Continue with X (formerly Twitter)",
    METAMASK: "Metamask",
    WALLET_CONNECT: "WalletConnect",
    POWERED_BY_TRIA: "Powered by Tria",
    OR: "OR",
    CREATE_YOUR_TRIA_NAME: "Create your Tria name",
    USERNAME: "Username",
    NEXT: "Next",
    "@tria": "@tria",
    TRIA_INFO:
        "is like Gmail, for Web3. Pay, receive and log-in to apps on any device, and blockchain.",
    YOUR: "Your",
    ASSETS_UP: "Assets Up",
    BUY: "Buy",
    SEND: "Send",
    CRYPTO: "Crypto",
};
